from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from .resnet_embedding import ResNet50
from .resnet_embedding import ResNet101
from .resnet_embedding import ResNet152
from .resnext_vd_embedding import ResNeXt50_vd_32x4d
from .resnext_vd_embedding import ResNeXt50_vd_64x4d
from .resnext_vd_embedding import ResNeXt101_vd_32x4d
from .resnext_vd_embedding import ResNeXt101_vd_64x4d
from .resnext_vd_embedding import ResNeXt152_vd_32x4d
from .resnext_vd_embedding import ResNeXt152_vd_64x4d
from .se_resnext_vd_embedding import SE_ResNeXt50_vd_32x4d
from .se_resnext_vd_embedding import SE_ResNeXt101_vd_32x4d
from .se_resnext_vd_embedding import SENet154_vd
from .efficientnet_embedding import EfficientNetB4
from .res2net_vd import Res2Net101_vd_26w_4s
from .res2net_vd import Res2Net50_vd_26w_4s
from .hrnet_embedding import HRNet_W64_C